### ISSUE TITLE
(Fatal error!) [ 0.85+1.3 ] Error connecting to the database mysql

### ISSUE THREAD

**Issue by AircraftRu** [pluginsGLPI/order#62] opened 2016-09-19 13:08 UTC
When upgrade the order plugin this error:

![helpdesk_glpi_front_plugin form php - google chrome 2016-09-19 16 01 45](https://cloud.githubusercontent.com/assets/17082164/18633038/0a8c41ac-7e83-11e6-9719-0c561a093d3a.png)

**Comment by trasher** [comment] 2016-10-27 06:03
I'm not sure about this issue. As far as I can see, the line causing the issue is just to rename an existing field, that should already have been `varchar(255)`; it should not be truncated.

Could you give us the existing table structure of `glpi_plugin_order_references` before any migration try?

**Comment by AircraftRu** [comment] 2016-10-27 11:08
Now I can't anymore. On the last job I don't work anymore. But I remember that in the new version there were no problems.

**Comment by trasher** [comment] 2016-10-27 12:10
Ok, I'll close this ticket then. Thank you for your feedback :)

**Closed by trasher** 2016-10-27 12:10 UTC
Labels: bug
